@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.idocalm.travelmate.models.Hotel#Hotel(int,String,String,double,double,long,String,String)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.idocalm.travelmate.models.Hotel",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1667077907 { 
   	label=idocalm
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_352704218 { 
   	label=travelmate
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1650280550 { 
   	label=Hotels
	labeljust=l
	fillcolor=white
	style=filled
   
   Hotels2016336877XXXfetchHotels1603317358[
	label="+ fetchHotels()"
	style=filled
	fillcolor=white
	tooltip="Hotels

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1832931529 { 
   	label=Hotel
	labeljust=l
	fillcolor=white
	style=filled
   
   Hotel1063277009XXXHotel1825589827[
	label="+ Hotel()"
	style=filled
	fillcolor=white
	tooltip="Hotel

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_291174691 { 
   	label=HotelsSearchFragment
	labeljust=l
	fillcolor=white
	style=filled
   
   HotelsSearchFragment588979362XXXonCreateView43515399[
	label="+ onCreateView()"
	style=filled
	fillcolor=white
	tooltip="HotelsSearchFragment

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
Hotels2016336877XXXfetchHotels1603317358 -> Hotel1063277009XXXHotel1825589827;
HotelsSearchFragment588979362XXXonCreateView43515399 -> Hotels2016336877XXXfetchHotels1603317358;
    
}
@enduml